export default {
  products: [
    {
      _id: 1,
      name: "Slim Shirt",
      image: "/images/d1.jpg",
      category: "Shirts",
      price: 80,
      brand: "Nike",
      rating: 4.6,
      numReviews: 17,
    },
    {
      _id: 2,
      name: "Fit Shirt",
      image: "/images/d2.jpg",
      category: "Shirts",
      price: 100,
      brand: "Nike",
      rating: 4.9,
      numReviews: 18,
    },
    {
      _id: 3,
      name: "Best Pant",
      image: "/images/d3.jpg",
      category: "Pants",
      price: 43,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
    },
    {
      _id: 4,
      name: "Slim Shirt",
      image: "/images/d4.jpg",
      category: "Shirts",
      price: 80,
      brand: "Nike",
      rating: 4.7,
      numReviews: 15,
    },
  ],
};
